
# use travis-ci docker based infrastructure
sudo: false

language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_script:
  - git submodule init
  - git submodule update --recursive

script:
  - ant
